name: imperium-news-streaming-platform

include:
  - compose/source.yml
  - compose/kafka.yml
  - compose/spark-cluster.yml
  - compose/spark-drivers.yml
  - compose/projectors.yml
  - compose/serving.yml
  - compose/backend.yml
  - compose/observability.yml
  - compose/ui.yml

networks:
  imperium-net:
    name: imperium-net
    driver: bridge

volumes:
  kafka-1-data:
    name: imperium-kafka-1-data
  kafka-2-data:
    name: imperium-kafka-2-data
  connect-data:
    name: imperium-connect-data
  redis-data:
    name: imperium-redis-data
  redisinsight-data:
    name: imperium-redisinsight-data
  observability-clickhouse-data:
    name: imperium-observability-clickhouse-data
  observability-hyperdx-mongo-data:
    name: imperium-observability-hyperdx-mongo-data
  observability-grafana-data:
    name: imperium-observability-grafana-data
  qdrant-data:
    name: imperium-qdrant-data
  elasticsearch-data:
    name: imperium-elasticsearch-data
  spark-master-data:
    name: imperium-spark-master-data
  spark-worker-1-data:
    name: imperium-spark-worker-1-data
  spark-worker-2-data:
    name: imperium-spark-worker-2-data
  spark-worker-3-data:
    name: imperium-spark-worker-3-data
  phase3-checkpoints:
    name: imperium-processing-checkpoints
  source-db:
    external: true
    name: source-db
  clone-news-state:
    name: imperium-clone-news-state
