CREATE TABLE IF NOT EXISTS public.table_news
(
    id serial NOT NULL,
    added_in timestamp without time zone NOT NULL DEFAULT now(),
    added_by integer NOT NULL DEFAULT 0,
    updated_in timestamp without time zone NOT NULL DEFAULT now(),
    updated_by integer NOT NULL DEFAULT 0,
    updated boolean NOT NULL DEFAULT false,
    link_id integer NOT NULL DEFAULT 0,
    more_url text NOT NULL DEFAULT ''::text,
    more_title text NOT NULL DEFAULT ''::text,
    more_inner_text text NOT NULL DEFAULT ''::text,
    more_reporter text NOT NULL DEFAULT ''::text,
    more_date_text text NOT NULL DEFAULT ''::text,
    more_image_url text NOT NULL DEFAULT ''::text,
    more_image_down boolean NOT NULL DEFAULT false,
    more_source_html_down boolean NOT NULL DEFAULT false,
    more_hash text NOT NULL,
    more_image_extension_id integer NOT NULL DEFAULT 0,
    more_image_size integer NOT NULL DEFAULT 0,
    article_id integer NOT NULL DEFAULT 0,
    article_applic_contenu_id integer NOT NULL DEFAULT 0,
    langue_id integer NOT NULL DEFAULT 0,
    langue_id_updated boolean NOT NULL DEFAULT false,
    more_title_updated boolean NOT NULL DEFAULT false,
    more_inner_text_updated boolean NOT NULL DEFAULT false,
    valide boolean NOT NULL DEFAULT false,
    checked boolean NOT NULL DEFAULT false,
    to_delete boolean NOT NULL DEFAULT false,
    more_meta_keywords text NOT NULL DEFAULT ''::text,
    more_meta_description text NOT NULL DEFAULT ''::text,
    more_trad_fr text NOT NULL DEFAULT ''::text,
    ss_jpg boolean NOT NULL DEFAULT false,
    ss_pdf boolean NOT NULL DEFAULT false,
    ss_jpg_size integer NOT NULL DEFAULT 0,
    ss_pdf_size integer NOT NULL DEFAULT 0,
    indexed boolean NOT NULL DEFAULT false,
    indexed_in timestamp without time zone NOT NULL DEFAULT now(),
    rubrique_id integer NOT NULL DEFAULT 0,
    rubric_checked boolean NOT NULL DEFAULT false,
    more_date_checked boolean,
    more_date_error_id integer,
    more_date_regex_text text,
    more_source_html character varying(256),
    readability boolean DEFAULT false,
    ss_rct boolean,
    ss_rct_size integer,
    authority_id integer DEFAULT 0,
    more_video_url text,
    indexed_s boolean,
    queried boolean,
    isvideo boolean NOT NULL DEFAULT false,
    pubdate timestamp without time zone,
    crawl_date timestamp without time zone,
    micro_service_id integer,
    article_payant boolean,
    CONSTRAINT table_news_pk PRIMARY KEY (id)
);
