CREATE TABLE IF NOT EXISTS imperium_news_articles (
    article_id VARCHAR(255) PRIMARY KEY,
    source_news_id BIGINT,
    link_id BIGINT,
    authority_id BIGINT,
    country_id INTEGER,
    country_name VARCHAR(255),
    source_name VARCHAR(255),
    source_domain VARCHAR(255),
    rubric_id INTEGER,
    rubric_title VARCHAR(255),
    language_id INTEGER,
    language_code VARCHAR(10),
    
    classification_status VARCHAR(50) NOT NULL,
    classification_method VARCHAR(100),
    classification_model VARCHAR(100),
    root_topic_id VARCHAR(100),
    root_topic_label VARCHAR(255),
    primary_topic_id VARCHAR(100),
    primary_topic_label VARCHAR(255),
    topic_confidence DOUBLE PRECISION,
    topic_candidates JSONB,
    
    title TEXT,
    url TEXT,
    body_text TEXT,
    body_text_clean TEXT,
    excerpt TEXT,
    image_url TEXT,
    video_url TEXT,
    reporter VARCHAR(255),
    source_date_text VARCHAR(255),
    published_at BIGINT,
    crawled_at BIGINT,
    is_video BOOLEAN,
    dimension_status VARCHAR(50),
    missing_dimensions JSONB,
    schema_version INTEGER,
    processed_at TIMESTAMP,
    is_delete BOOLEAN,
    classified_at TIMESTAMP,
    
    embedding_vector REAL[],
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
